language: cpp

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get update && sudo apt-get install -y libgtkmm-3.0-dev mm-common autoconf automake libtool doxygen pkg-config g++-4.8 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50 ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install gtkmm3 plplot mm-common && brew link --force gtkmm3 plplot mm-common ; fi

install:
  - wget https://downloads.sourceforge.net/project/plplot/plplot/5.10.0%20Source/plplot-5.10.0.tar.gz
  - tar xfz plplot-5.10.0.tar.gz
  - cd plplot-5.10.0
  - mkdir our_build
  - cd our_build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
  - make
  - sudo make install

script:
  - autoreconf -fi && ./configure && make

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

#os:
#  - osx

