language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libgtkmm-3.0-dev mm-common libplplot-c++11 libplplot-dev plplot12-driver-cairo ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install gtkmm3 plplot mm-common && brew link --force gtkmm3 plplot mm-common ; fi

script:
  - autoreconf -fi
  - ./configure && make

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

#os:
#  - osx

