language: cpp

compiler:
  - gcc

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
 
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:kalakris/cmake -y && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get update && sudo apt-get install -y libffi-dev mm-common autoconf automake libtool doxygen pkg-config g++-4.8 cmake libpng12-dev gettext libfreetype6-dev libfontconfig1-dev libjpeg-dev libtiff4-dev && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50 ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install gtkmm3 plplot mm-common && brew link --force gtkmm3 plplot mm-common ; fi

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then ./travis-deps.sh ; fi

script:
  - autoreconf -fi && ./configure && make

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

#os:
#  - osx

