language: cpp

sudo: required

compiler:
  - gcc
  #- clang

os:
  - linux
  - osx

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - LD_RUN_PATH=/usr/local/lib

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then ./travis-before-install-linux.sh ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install gtkmm3 plplot mm-common boost && brew link --force gtkmm3 plplot mm-common ; fi

#install:
#  - if [ $TRAVIS_OS_NAME == linux ]; then ./travis-deps.sh ; fi

script:
  - autoreconf -fi && ./configure LDFLAGS="-Wl,-rpath -Wl,/usr/local/lib" && make

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

#os:
#  - osx
